### ISSUE TITLE
wont compile

### ISSUE THREAD

**Issue by steamgamemodder** [CrypticOS/crypticos#1]
It says the kernel folder does not exist

**Comment by petabyt** [comment]
Try `nasm -f bin mini.asm -o boot.bin`

**Comment by steamgamemodder** [comment]
"booting from hard disk" when running the binary

**Comment by petabyt** [comment]
Try typing in `!%***.` and enter.

**Comment by steamgamemodder** [comment]
how does this work

**Comment by steamgamemodder** [comment]
nvm i read the readme

**Comment by petabyt** [comment]
Basically, it is a prompt. You type in code, and it runs it.
It uses my own 16 character instruction set, which my higher level language compiles to: https://github.com/pufflegamerz/crypticdk
